spring.application.name=carbon-credit
spring.data.mongodb.uri=mongodb://localhost:27017/carbon_credit_db
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.mongodb.autoconfigure.MongoDBAtlasVectorStoreAutoConfiguration
server.port=8080